### ISSUE TITLE
Force field generator? 

### ISSUE THREAD

**Issue by iKiba** [andersmmg/LockAndBlock#2]
Testing out the mod, the force field generator does not seem to work, it indicates that theres a redstone signal to it however it does nothing else? 

![image](https://github.com/andersmmg/LockAndBlock/assets/123995156/996bbc0c-3bf7-4928-b430-a16c61b36df3)

**Comment by andersmmg** [comment]
You need 2 generators facing each other, then when one is powered creates a field between them

**Comment by iKiba** [comment]
Thank you, had no idea!

**Comment by andersmmg** [comment]
I plan to add some sort of in-game documentation soon, hopefully that'll help
