### ISSUE TITLE
Crash when used with lunar client.

### ISSUE THREAD

**Issue by charim09** [andersmmg/LockAndBlock#5]
Crashed on launch when using lunar client 1.20.1

**Comment by andersmmg** [comment]
We don't support other clients, but I can see if it's a simple issue. Can you send the crash log?

**Comment by charim09** [comment]
[crash-2024-09-14_20.43.53-client.txt](https://github.com/user-attachments/files/17003305/crash-2024-09-14_20.43.53-client.txt)

**Comment by charim09** [comment]
Thank you for checking it anyway.

**Comment by andersmmg** [comment]
They just sometimes change things that break some mods, so it's hard to support all of them. In this case it looks like you just didn't install the owo library, which this mod requires

**Comment by charim09** [comment]
I think I've sent you an old crash file, I have owo lib let me just post a new one.
[0094c3f4-512a-42e3-9969-199f26fce50a-master.log](https://github.com/user-attachments/files/17003977/0094c3f4-512a-42e3-9969-199f26fce50a-master.log)
Idk if this works... I didn't get a crash report this time weirdly, it's just this booting error.

**Comment by charim09** [comment]
I have both Lavender and owolib installed which I believe this mod requires.

**Comment by andersmmg** [comment]
Does it boot if you disable lock & block?

**Comment by charim09** [comment]
It boots without L&B and it's requirements(owo and lavender) but I did a few trial and error and it doesn't boot while owo or lavender is loaded. So I think the problem is these 2 libs. Lunar client has it's own dependencies files which has both Lavender and owo related files in it. but when I try to uninstall client downloads them again. So I dont know what to do. Sorry for taking your time I guess the dependencies are the problem

**Comment by andersmmg** [comment]
Yeah, from looking at the logs, it looks like it's some sort of incompatibility between owo and lunar client. Not sure beyond that
