### ISSUE TITLE
ПЛИЗ ПОРТИРУЙ НА НЕОФОРДЖ | PLEASE PORT TO NEOFORGE

### ISSUE THREAD

**Issue by DamageWorld** [andersmmg/LockAndBlock#6]
Я хочу использовать этот мод на моей сборке вместе с модом SecurityCraft.
I want to use Lock & Block mod on my build with SecurityCraft mod.

**Comment by andersmmg** [comment]
Sorry, this mod only supports Fabric and I have no plans to port to other loaders. Feel free to fork and port it yourself
